<?php

namespace frontend\controllers;
use frontend\models\Workers;
use yii\data\Pagination;

class IndexController extends \yii\web\Controller
{
     public function beforeAction($action)
     {
         define('CACHT_TIME',24*60*60);  //设置缓存时间
         define('CACHT_ON','false');    //设置是否开启缓存
         return parent::beforeAction($action); // TODO: Change the autogenerated stub
     }

    public function actionIndex()
    {
        $cache=\Yii::$app->cache;
        $get=$cache->get('main');
        $model=new Workers();
        if(CACHT_ON=='true')
        {
            if($get)
            {  //存在
                if(time()-$get['time']>=CACHT_TIME)
                {  //过期了
                    $info=$model->find()->orderBy('sort desc')->limit(3)->asArray()->all();
                    $data['data']=$this->render('index',['userinfo'=>$info]);
                    $data['time']=time();
                    $cache->set('main',$data,CACHT_TIME);
                    echo $data['data'];die;
                } //没过期
                echo $get['data'];
            }else
            {//不存在
                $info=$model->find()->orderBy('sort desc')->limit(3)->asArray()->all();
                $data['time']=time();
                $data['data']=$this->render('index',['userinfo'=>$info]);
                $cache->set('main',$data,CACHT_TIME);
                echo $data['data'];
            }
        }else
        {
            $info=$model->find()->orderBy('sort desc')->limit(3)->asArray()->all();
            return $this->render('index',['userinfo'=>$info]);
        }
    }


    public function actionAbout()
    {
        return $this->render('about');
    }
    public function actionDelete()
    {
        $chache=\Yii::$app->cache;
        $chache->delete('main');
    }

    public function actionStaff()
    {
        $model=new Workers();
        $data = $model->find();
        $pages = new Pagination(['totalCount' =>$data->count(), 'pageSize' => '6']);
        $info = $data->offset($pages->offset)->limit($pages->limit)->all();
        return $this->render('staff',['info' => $info,'pages' => $pages]);
    }

}
